aplicaciones/login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name ="login"

urlpatterns = [
    #path('', views.Index.as_view(), name='index'),
    
    path('login/', views.Login.as_view() ,name="login"),
    path('logout/', views.Logout.as_view() ,name="logout"),




    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/principal/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns #Pendiente con esto

from . import views

app_name ="principal"

urlpatterns = [
    #path('', views.Index.as_view(), name='index'),
    
    path('', views.Index.as_view() ,name="index"),
    path('about', views.about ,name="about"),




    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

solanko/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns #Pendiente con esto para traducciones

urlpatterns = [

    #Traducciones
    #path('i18n/', include('django.conf.urls.i18n')),

    path('admin/', admin.site.urls),

    
]


urlpatterns += i18n_patterns(

    path('', include('aplicaciones.principal.urls')),
    path('', include('aplicaciones.login.urls')),
    path('', include('aplicaciones.usuarios.urls')),
    path('', include('aplicaciones.correos.urls')),
    path('', include('aplicaciones.fondo_imagenes.urls')),
    path('', include('aplicaciones.chats.urls')),
    path('', include('aplicaciones.yates.urls')),
    #path('login', include('login.urls')),


    #TODO LO RELACIONADO A LAS APIS
    path('api-auth/', include('rest_framework.urls')),
    path('', include('aplicaciones.usuarios.api.urls')),
    path('', include('aplicaciones.correos.api.urls')),
    
    
    
    prefix_default_language=False, #Por defecto se usa el lenguaje asignado en setting
 )

aplicaciones/principal/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render

from django.contrib.auth import authenticate#Para autenticar a los usuarios
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout

#Para enviar mensajes a correos
from django.core.mail import EmailMessage
from django.template.loader import render_to_string



#Decoradores
from django.views.decorators.csrf import csrf_protect

#Traducciones
from django.utils.translation import gettext as _



#Clases para las plantillas
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView, DeleteView


#Modelo de usuarios
from aplicaciones.usuarios.models import Usuarios

    



class Index(TemplateView):

    template_name = "principal/index.html"

    def dispatch(self, request, *args, **kwargs):

        """
        if request.user.is_anonymous:
            print("No estas autenticado, eres un usuario anonimo")
            return redirect("login:login")

        else:

            print("Estas autenticado GENIAL",request.user)
            print("usuario: ",request.user)
            print("usuario permisos: ",request.user.get_all_permissions())
            print(request.user.has_perm('src.ver_zulia'))
        
            
            #Aqui verificamos si el usuario esta activo para que ingrese
            
            if request.user.activo:   
                print("Usuario activo y validado")
            else:
                print("El usuario no esta activo")
                messages.add_message(request, messages.INFO, "Usuario Inactivo")
                return redirect("src:logout")
        """

            #return redirect("src:index")
            #print("Usuario ",request.user)

            #Esto es algo que podria funcionar en algun momento
            #grupo="prueba"
            #print('Proyecto %s' % (grupo))


        
        user = authenticate(username='admin', password='1')
        if  user is None:
            print("El usuario no se ha autenticado ")


            print("Probando cosas jajajaj")

            

            # A backend authenticated the credentials
        else:
            print("El usuario es este: ",user)
            
            #print(request)
            
            #do_login(request, user)
            # No backend authenticated the credentials
            

            
            #empresa_creada = Empresa.objects.filter(creado_por_id=request.user.id)

        print("usuario: ",request.user)

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['informacion'] = "Hola..."



#Para pruebas
@csrf_protect
def home(request):
     # Si estamos identificados devolvemos la portada
    
    contexto = {"Traduccion":_("Welcome to my site.")} 
    print(_("Welcome to my site."))
    return render(request, "principal/index.html", contexto)


@csrf_protect
def about(request):
     # Si estamos identificados devolvemos la portada
    
    contexto = {"Traduccion":_("Welcome to my site.")} 
    print(_("Welcome to my site."))
    return render(request, "principal/about.html", contexto)

aplicaciones/principal/templates/base.html
<!doctype html>
{% load static %}
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    {% block EnlacesBootstrap5 %}
    <!-- Bootstrap CSS -->

    
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-5.2.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'principal/css/estilo.css' %}">
  
  <!-- Icono de la pagina -->
  <link id="iconPagWeb" rel="shortcut icon" href="{% static 'principal/img/loteria.jpg' %}" type="image/x-icon">

    {% endblock %}

    {% block EnlacesPlantilla_Base %}

    <link rel="stylesheet" href="{% static 'vendor/plantilla_base/css/styles.css' %}">
    <!-- JavaScript Fontawesome -->
    <script src="{% static 'vendor/plantilla_base/js/fontawesome6-1-0-all.js' %}" crossorigin="anonymous"></script>
          

    


    {% endblock %}

    {% block EnlacesPlantillas %}

    


    {% endblock %}

    {% block EnlacesPersonalizados %}

    

    

    {% endblock %}
    
    <title>{% block titulo %}BASE {% endblock %}</title> 

  </head>

  <body class="sb-nav-fixed">
    {% block menu_superior %}
      <!--Aqui se incluye el menu superior-->
      {% include "menu_superior.html" %}
    
      {% endblock%}


    
    
    

    
    {% block contenedor %} 

    <div id="layoutSidenav">
    
        <!--Aqui se incluye el menu lateral-->
        {% include "menu_dashboar.html" with tema="index" subtema=""   %}


        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <h1 class="mt-4">Dashboard</h1>
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                    <div class="row">
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-primary text-white mb-4">
                                <div class="card-body">Primary Card</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="#">View Details</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-warning text-white mb-4">
                                <div class="card-body">Warning Card</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="#">View Details</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-success text-white mb-4">
                                <div class="card-body">Success Card</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="#">View Details</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-danger text-white mb-4">
                                <div class="card-body">Danger Card</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="#">View Details</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="card mb-4">
                                <div class="card-header">
                                    <i class="fas fa-chart-area me-1"></i>
                                    Area Chart Example
                                </div>
                                <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="card mb-4">
                                <div class="card-header">
                                    <i class="fas fa-chart-bar me-1"></i>
                                    Bar Chart Example
                                </div>
                                <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            DataTable Exampleasasasasas
                        </div>
                        
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>


    </div>
            
          
    {% endblock %}


    {% block footer %}


    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Your Website 2022</div>
                <div>
                    
                </div>
            </div>
        </div>
    </footer>

        


    {% endblock %}
  

    
    

    
    

    {% block EnlacesGraficas_js %}

      
    
    {% endblock %}


    {% block EnlacesListado_js %}

       

    {% endblock %}


    {% block EnlacesBootstrap5js %}


          

          <!-- JavaScript Bundle with Popper -->
          <script src="{% static 'vendor/bootstrap-5.2.1-dist/js/bootstrap.bundle.min.js' %}"  crossorigin="anonymous"></script>
          
          
          

          

          
    {% endblock %}

    {% block EnlacesPlantillas_base %}

    <script src="{% static 'vendor/plantilla_base/js/scripts.js' %}"></script>
    
    {% endblock%}

    
  </body>
</html>

aplicaciones/principal/templates/menu_dashboar.html
{% load static %}
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
          <div class="nav">
              <div class="sb-sidenav-menu-heading"></div>
              <a class="nav-link" href="{% url 'principal:index' %}">
                  <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                  Inicio {{perms.juegos.iniciarjugada}}
              </a>
              <!--<div class="sb-sidenav-menu-heading"></div>--->
              <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                  <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                  Jugadas
                  <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
              </a>
              <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                  <nav class="sb-sidenav-menu-nested nav">
                    {% if perms.juegos.iniciarjugada %}
                        <a class="nav-link" href="{% url 'juegos:iniciarJugada' %}">Iniciar Jugada</a>
                    {% endif %}
                      
                    {% if perms.juegos.consultarjugada %}
                        <a class="nav-link" href="{% url 'juegos:consultarJugada' %}">Consultar Jugadas</a>
                    {% endif %}
                    
                      
                      
                  </nav>
              </div>
              
              {% if perms.juegos.informejugada %}
                <a class="nav-link" href="{% url 'informes:informarJugada' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                    Informes
                </a>
              {% endif %}
              
              
              <!--
              <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                  <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                      <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                          Authentication
                          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                      </a>
                      <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                          <nav class="sb-sidenav-menu-nested nav">
                              <a class="nav-link" href="login.html">Login</a>
                              <a class="nav-link" href="register.html">Register</a>
                              <a class="nav-link" href="password.html">Forgot Password</a>
                          </nav>
                      </div>
                      <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                          Error
                          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                      </a>
                      <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                          <nav class="sb-sidenav-menu-nested nav">
                              <a class="nav-link" href="401.html">401 Page</a>
                              <a class="nav-link" href="404.html">404 Page</a>
                              <a class="nav-link" href="500.html">500 Page</a>
                          </nav>
                      </div>
                  </nav>
              </div>

              -->

              <!-- 
              <div class="sb-sidenav-menu-heading">Addons</div>
              <a class="nav-link" href="charts.html">
                  <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                  Charts
              </a>
              <a class="nav-link" href="tables.html">
                  <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                  Tables
              </a>
              -->
          </div>
      </div>
      <div class="sb-sidenav-footer">
          <div class="small">Usuario: {{user}}</div>
          
      </div>
  </nav>
</div>

aplicaciones/principal/templates/menu_superior.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <!-- Navbar Brand-->
  <a class="navbar-brand ps-3" href="#">Relancino</a>
 <!-- Navbar Search-->
  <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
      
  </form>
  <!-- Navbar-->
  <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <!---
              <li><a class="dropdown-item" href="#!">Configuraciones</a></li>
              <li><a class="dropdown-item" href="#!">Activity Log</a></li>
              <li><hr class="dropdown-divider" /></li>
            -->
              <li><a class="dropdown-item" href="{% url 'login:logout' %}">Cerrar sesion</a></li>
          </ul>
      </li>
  </ul>
</nav>