aplicaciones/login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name ="login"

urlpatterns = [
    #path('', views.Index.as_view(), name='index'),
    
    path('login/', views.Login.as_view() ,name="login"),
    path('logout/', views.Logout.as_view() ,name="logout"),




    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/usuarios/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name ="usuarios"

urlpatterns = [
    #path('', views.Index.as_view(), name='index'),
    
    path('registrar', views.registrar.as_view() ,name="registrarUsuario"),



    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

solanko/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns #Pendiente con esto para traducciones

urlpatterns = [

    #Traducciones
    #path('i18n/', include('django.conf.urls.i18n')),

    path('admin/', admin.site.urls),

    
]


urlpatterns += i18n_patterns(

    path('', include('aplicaciones.principal.urls')),
    path('', include('aplicaciones.login.urls')),
    path('', include('aplicaciones.usuarios.urls')),
    path('', include('aplicaciones.correos.urls')),
    path('', include('aplicaciones.fondo_imagenes.urls')),
    path('', include('aplicaciones.chats.urls')),
    path('', include('aplicaciones.yates.urls')),
    #path('login', include('login.urls')),


    #TODO LO RELACIONADO A LAS APIS
    path('api-auth/', include('rest_framework.urls')),
    path('', include('aplicaciones.usuarios.api.urls')),
    path('', include('aplicaciones.correos.api.urls')),
    
    
    
    prefix_default_language=False, #Por defecto se usa el lenguaje asignado en setting
 )

aplicaciones/usuarios/models.py
import os
import shutil #libreria para borrar carpetas esten o no llenas
from django.conf import settings
from django.db import models

#Estos dos modelos son para crear permisos personalizados
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_save, pre_delete, post_delete


# Create your models here.

##################################################################################################
####################### Modelos para Usuarios ####################################################


class UsuarioManager(BaseUserManager):

    def create_user(self,email,password=None,admin = False,is_superuser =False,plan_elegido="gratis"):
        print("Creamos Usuario Normal")
        #if not email:
        #    raise ValueError('El usuario debe tener un correo electronico')

        usuario = self.model(
            
            #username = username,
            email = self.normalize_email(email),
            password = password,
            #rol = rol,
            admin =admin,
            is_superuser = is_superuser,
            #plan_elegido = plan_elegido,
        )

        #aqui encriptamos la clave para no guardar en texto plano
        print("ENCRIPTAMOS", password)
        usuario.set_password(password)
        usuario.save()
        return usuario
    
    

    #Funcion para usuario administrador
    def create_superuser(self,email,password,admin = True,is_superuser = True):
        print("Creamos superusuario")

        usuario = self.create_user(
            email = email,  
            #username = username,
            #rol = rol,
            #plan_elegido = plan_elegido,
            password = password,
            admin =admin,
            is_superuser = is_superuser
        )
        
            
            
        print("Entramos en superuser")
        usuario.save()
        return usuario


#Funcion para agregar carpetas al usuario
def direccion_usuarios(instance, filename):
  
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    print(instance)
    print(instance.id)
    print(instance.email)
    return 'usuarios/fondos/{0}/{1}'.format(instance.email, filename)


# Heredamos de AbstractBaseUser para adaptarlo a nuestro gusto
class Usuarios(AbstractBaseUser,PermissionsMixin):

    #(Lo que se guarda en bases de datos, lo que se ve al usuario)
    usuario_tipos = [
        ('master','Master'),
        ('operadora','Operadora'),
        ('distribuidora','Distribuidora'),
        ('subdistribuidor','Subdistribuidor'),
        ('agencia','agencia'),
        ('normal','Normal'),
    ]

    #tipo_plan = [
    #    ('gratis','Free'),
    #    ('pago','Pay'),
    #]
    
    id = models.AutoField(primary_key=True)
    #username = models.CharField("Username",max_length=200,unique=True)
    nombre = models.CharField("Nombre",max_length=200,blank=True, null=True) 
    apellido = models.CharField("Apellido",max_length=200,blank=True, null=True) 
    email = models.EmailField("Correo Electronico",max_length=150, unique=True)
    activo = models.BooleanField(default=True)#Para poder ingresar al sistema  
    is_superuser = models.BooleanField(default=False)#Este es superusuario
    admin = models.BooleanField(default=False)#Para poder ingresar al admin de django
    cedula = models.IntegerField(default=0,blank=True, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True) 
    ultimo_ingreso = models.DateTimeField('actualizado', auto_now=True)
    direccion = models.CharField("Direccion",max_length=100,blank=True, null=True,default="Las Adjuntas") 
     
    
    rol = models.CharField("Rol",max_length=150,choices=usuario_tipos,default='normal',blank=True, null=True)

    #plan_elegido = models.CharField("Plan",
    #    max_length=150,
    #    choices=tipo_plan,    
    #    default='libre'
    #)

    telefono = models.CharField("Telefono", max_length=50,blank=True,null=True,default="04242020470")
    #imagenFondoEscritorio = models.ImageField("Imagen de Escritorio", upload_to=direccion_usuarios, max_length=200,blank=True,null=True)
    
    #Para enlazar al manager que has creado
    objects = UsuarioManager()

    USERNAME_FIELD = 'email'  #Para estableccer este campo como unico
    REQUIRED_FIELDS = ['is_superuser'] # Campos obligatorios(los pide cuando los creas por consola)

    def __str__(self):
        return f'{self.email}'
    
    
    
    #para verificar si un usuario es administrador o no(Para entrar en el admin)
    @property
    def is_staff(self):
         # "Is the user a member of staff?"
         if self.activo:
            return self.admin
         return False
     

    def has_module_perms(self, app_label):
        return True

    

################# AQUI HACEMOS TODAS LAS PRUEBAS #########################




    def save(self, *args, **kwargs):
        
        super(Usuarios, self).save(*args, **kwargs)
        
        
        
        #print(self.id)
        #print("metodo jajajaj:",self._state.adding)



    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'
        db_table = 'usuarios'
        
        permissions = [
            #(Lo que se guarda en bases de datos, lo que se ve al usuario)
            #Permisos para master y gerente
            #("permisoscompletos", "Permisoscompletos"),
            
            
            
            
            
            
        ]#Fin de los permisos




    


##########################################################################################################
##########################################################################################################

aplicaciones/usuarios/views.py
from django.shortcuts import render, redirect
from aplicaciones.usuarios.models import Usuarios


#Clases para las plantillas
from django.views.generic import View,TemplateView, CreateView, UpdateView, DetailView, ListView, DeleteView

# Create your views here.




class registrar(TemplateView):

    template_name = "usuarios/registrarUsuario.html"

    def dispatch(self, request, *args, **kwargs):

        print("Estas autenticado GENIAL")
        #print("Permisos: ",list(Permission.objects.all()))
        print("usuario: ",request.user)



        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['informacion'] = "Hola..."

        
        
        return context



"""
class ProductosCrear(CreateView):

    model = Usuarios  
    form_class = ProductoForm
    template_name = "productos/productos-crear.html"
    success_url = reverse_lazy('productos:ProductoListar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['informacion'] = "Hola..."
        context['titulo'] = "Crear Productos"
        context['usuario'] = self.request.user
        return context

    def post(self,request,*args,**kwargs):
        
        print("entrando en post")

        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()#Guardamos el objeto
            return HttpResponseRedirect(self.success_url)

        #En caso de que no se cree el self.object se coloca en None
        self.object = None
        print(form.errors)

        #Aqui llamamos a todas las variables establecidas en get_context
        context = self.get_context_data(**kwargs)
        context['form'] = form

        #Asi es otra forma de enviar el contexto
        return render(request,self.template_name,context)
        
        #Asi es una forma de enviar
        #return render(request,self.template_name,{"form":form})

"""

aplicaciones/usuarios/templates/usuarios/registrarUsuario.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <title>Solanko</title>
                                
        <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %}' rel='stylesheet'>
        <link href="{% static 'principal/assets/images/favicon/favicon-16x16.png' %}" rel="icon">

        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/vendor/bootstrap/css/bootstrap.min.css' %}">

        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/fonts/iconic/css/material-design-iconic-font.min.css' %}">

        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/vendor/animate/animate.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Great+Vibes%7CKaushan+Script%7CRaleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" type="text/css">

        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/vendor/css-hamburgers/hamburgers.min.css' %}">

        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/vendor/animsition/css/animsition.min.css' %}">

        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/vendor/select2/select2.min.css' %}">

        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/vendor/daterangepicker/daterangepicker.css' %}">

        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/css/util.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/revolution/css/settings.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/revolution/css/layers.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'principal/assets/revolution/css/navigation.css' %}">
        <link rel="stylesheet" href="{% static 'principal/assets/css/fuentes.css' %}">
        <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>

        <!---fin del div main active---->
        <link rel="stylesheet" type="text/css" href="{% static 'usuarios/css/registro.css' %}">

    </head>
    <body className='snippet-body'>
        <div class="container-login100" style="background-image: url('/static/principal/assets/images/bg-04.jpg');">    
            <div class="container">
                <div class="card">





                   <!-- <form action="#" class="" id="FormRegistrosUsuarios" method="post">---->
                    <!-- {% csrf_token %}  ---->
                        
                        <div class="form"> 
                            <div class="left-side">
                                <ul class="progres_bar"> 
                                    <li>Personal Vitae</li>
                                    <li>Verification code</li> 
                                    <li>Finish</li>
                                </ul> 
                            </div> 
                            <div class="right-side "> 
                                <div class="main active"> 
                                    <div class="manage"> 
                                        <h3>Create account</h3>
                                        <p> A verification code will be sent to your cell phone and email </p> 
                                        </div> 
                                        
                                        <div class="input_div"> 
                                            <div class="input_text">
                                                <input class="written_name" name="nombreUsuario" value="pedro"  type="text" id="nombreUsuario"  required> 
                                                <label>First Name</label>
                                            </div> 
                                            <div class="input_text"> 
                                                <input type="text" name="apellidoUsuario" value="mendoza" id="apellidoUsuario" required>
                                                <label>Last Name</label> 
                                            </div> 
                                        </div>

                                        <div class="input_div">
                                            <div class="input_text"> 
                                                <input type="text"  name="emailUsuario" value="pedro@gmail.com" id="emailUsuario" required>
                                                <label>Email</label> 
                                            </div>
                                            <div class="input_text">
                                                <input type="number" name="telefonoUsuario" value="04125488855" id="telefonoUsuario" required> 
                                                <label>Phone </label> 
                                            </div>
                                        </div>
                                        <div class="input_div">

                                            <div class="input_text">
                                                <input class="pass_type" type="password" value="1" name="password1" id="password1" required>
                                                <label>Password</label> 
                                                <i class="fa fa-eye-slash password_eye"></i>
                                            </div> 

                                            <div class="input_text">
                                                <input class="confirm_pass_type" type="password" value="1" name="password2" id="password2" required> 
                                                <label>Confirm Password</label>
                                                <i class="fa fa-eye-slash con_eye"></i>
                                            </div>

                                        </div>

                                        <div class="agree"> 

                                            <span><i class="fa fa-check"></i></span>
                                            <p>I agree to the <a > Terms of Service</a>.</p>
            
                                        </div> 

                                        <div class="button step_1">
                                            <button class="next_btn">Next</button> 
                                        </div>
                                </div><!---fin del div main active---->

                                <div class="main">

                                    <div class="manage">

                                        <h3>A code has been sent to verify your account</h3>
                                        <p>A code has been sent to your email, please enter it</p>

                                    </div> 
                                                                        
                                                                            
                                    <div class="input_div"> 

                                        <div class="input_text"> 

                                            <input type="text" name="codigo_verificacion" id="codigo_verificacion" required> 
                                            <label placeholder="- - - - -">Verification code</label>

                                        </div>

                                    </div> 

                                    <div class="button step_2 m_top"> 

                                        <button class="prev_btn">Previous</button>
                                        <button class="next_btn">Next</button>

                                    </div>

                                </div> <!---fin del div main---->
                                                                                    
                                <div class="main "> 

                                    <div class="manage">
                                        <h3>Last details</h3>
                                        <p>Type "OK" and click the "Finish" button to finish creating the account to verify that you are not a robot.</p>
                                    </div> 

                                    <div class="input_div">

                                        <div class="input_text">
                                            <input type="text"  name="accion_final" id="accion_final" required>
                                            <label>"OK"</label>.
                                        </div> 

                                    </div> 
                                    <div class="agree_submit">

                                        <span><i class="fa fa-check"></i></span>
                                        <p>I hereby declare that information provided in the online registration form is true to the best of my knowledge and I accept motes,terms,disclaimer and policies by clicking "Finish" button.</p> 
                                    
                                    </div> 

                                    <div class="button step_2 step_4">

                                        <button class="prev_btn">Previous</button> 
                                          <button class="sbmt_btn">Finish</button>
                                       <!--- <button class="next_btn">Finish</button>---->
                                    </div> 

                                </div> <!---fin del div main---->


                                <div class="main ">
                                    <div class="manage"> 

                                        <h3>Congratulations 
                                            <span class="shown_name"></span>
                                        </h3> 
                                        <p>Your buisness account have been successfully registered.</p> 

                                    </div> 

                                    <svg class="checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52">
                                    <circle class="checkmark__circle" cx="26" cy="26" r="25" fill="none" /> 
                                    <path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8" />
                                    </svg>

                                    <div class="h4_txt"> 
                                        <a href="{% url 'login:login' %}"><button type="button" class="btn btn-primary">Iniciar Sesion</button></a>
                                        
                                    </div> 
                                </div>  <!---fin del div main---->

                            </div><!---fin del div right-side---->
                        </div><!---fin del div form---->


                    <!--</form>  ---->






                </div><!---fin del div card---->
        
            </div><!---fin del div container---->
        </div><!---fin del div container-login100---->

        <!-- JavaScript Bundle with Popper SWEEALERT2 -->
        <script src="{% static 'vendor/sweetalert2/sweetalert2.all.js' %}"  crossorigin="anonymous"></script>
       
        
    
        <script src="{% static 'usuarios/js/variables.js' %}"></script>
        <script src="{% static 'usuarios/js/cookiesDjango.js' %}"></script>
        <script src="{% static 'usuarios/js/registro.js' %}"></script>


        
                                    
    </body>

</html>